language:
    - objective-c

install:
    - brew install cmake
    - brew install ninja

script:
    - cmake --version
    - pwd
    - ls
    - mkdir build
    - cd build
    - cmake -G Ninja ..
    - ninja
