language: c

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
        - os: osx

script:
    - export CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}:/usr/local/opt/qt5"
    - ./build.sh
