language:
    - objective-c

install:
    - brew install cmake
    - brew install ninja
    - time brew install qt5

script:
    - export CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}:/usr/local/opt/qt5"
    - cmake --version
    - pwd
    - ls
    - mkdir build
    - cd build
    - cmake -G Ninja ..
    - ninja
